### ISSUE TITLE
Implement Dark mode

### ISSUE THREAD

**Issue by matt-j-deasy** [matt-j-deasy/collab-city#10]
No app is complete without a dark mode!  For now, we will have a simple button that changes the apps background to be either white or black. 

- [x] Save the current color as a state variable in the App component.  
- [x] Implement the "toggleDarkMode" function to switch the state variable from one color to another

**Comment by michael-oppenheimer** [comment]
Implemented Dark Mode Successfully

No breaking changes

![image](https://user-images.githubusercontent.com/76538596/103568525-adebc180-4e93-11eb-92f0-25d2ab9251c9.png)
