### ISSUE TITLE
Tests are failing!

### ISSUE THREAD

**Issue by matt-j-deasy** [matt-j-deasy/collab-city#5]
We have added a testing framework to our project.  Its called Jest!  Its all setup and ready to go, with some tests written out.  However the tests are failing 😢 This is because someone forgot to implement the method "orderPostsByCreatedDate".  This function needs to be properly implemented to allow the tests to pass. So heres what we need:

- [x] Implement the function orderPostsByCreatedDate
- [x] Ensure the tests pass by running the command `yarn test`

**Comment by michael-oppenheimer** [comment]
should be all good

**Comment by michael-oppenheimer** [comment]
wait

**Comment by matt-j-deasy** [comment]
@michael-oppenheimer Why'd you reopen this issue?

**Comment by michael-oppenheimer** [comment]
Oops it was when I was confused about not pulling the origin -- all good.
