### ISSUE TITLE
Remove the stale branch

### ISSUE THREAD

**Issue by matt-j-deasy** [matt-j-deasy/collab-city#7]
The branch: `michaels-first-issue` got merged into master successfully! However, it still exists.  Its good form to delete branches after you merge them to keep the repository tidy.  The history of the branch is easily accessible through the commit history so theres no harm in deleting it. So for this issue:

- [x] Delete the branch `michaels-first-issue` from the repository

**Comment by michael-oppenheimer** [comment]
yes
